//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Xml", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Xml : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.ResultadoPesquisa[] listaDeResultadosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.ResultadoPesquisa[] listaDeResultados {
            get {
                return this.listaDeResultadosField;
            }
            set {
                if ((object.ReferenceEquals(this.listaDeResultadosField, value) != true)) {
                    this.listaDeResultadosField = value;
                    this.RaisePropertyChanged("listaDeResultados");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultadoPesquisa", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResultadoPesquisa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string linkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string titulo {
            get {
                return this.tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.tituloField, value) != true)) {
                    this.tituloField = value;
                    this.RaisePropertyChanged("titulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                if ((object.ReferenceEquals(this.linkField, value) != true)) {
                    this.linkField = value;
                    this.RaisePropertyChanged("link");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AtakWS_PesquisaGoogle.PesquisaGoogleSoap")]
    public interface PesquisaGoogleSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldResponse HelloWorld(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldResponse> HelloWorldAsync(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name valorDaPesquisa from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EfetuaPesquisa", ReplyAction="*")]
        Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaResponse EfetuaPesquisa(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EfetuaPesquisa", ReplyAction="*")]
        System.Threading.Tasks.Task<Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaResponse> EfetuaPesquisaAsync(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EfetuaPesquisaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EfetuaPesquisa", Namespace="http://tempuri.org/", Order=0)]
        public Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequestBody Body;
        
        public EfetuaPesquisaRequest() {
        }
        
        public EfetuaPesquisaRequest(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EfetuaPesquisaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string valorDaPesquisa;
        
        public EfetuaPesquisaRequestBody() {
        }
        
        public EfetuaPesquisaRequestBody(string valorDaPesquisa) {
            this.valorDaPesquisa = valorDaPesquisa;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EfetuaPesquisaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EfetuaPesquisaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaResponseBody Body;
        
        public EfetuaPesquisaResponse() {
        }
        
        public EfetuaPesquisaResponse(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EfetuaPesquisaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.Xml xml;
        
        public EfetuaPesquisaResponseBody() {
        }
        
        public EfetuaPesquisaResponseBody(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.Xml xml) {
            this.xml = xml;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PesquisaGoogleSoapChannel : Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PesquisaGoogleSoapClient : System.ServiceModel.ClientBase<Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap>, Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap {
        
        public PesquisaGoogleSoapClient() {
        }
        
        public PesquisaGoogleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PesquisaGoogleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PesquisaGoogleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PesquisaGoogleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldResponse Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap.HelloWorld(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequest inValue = new Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequest();
            inValue.Body = new Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequestBody();
            Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldResponse retVal = ((Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldResponse> Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap.HelloWorldAsync(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldResponse> HelloWorldAsync() {
            Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequest inValue = new Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequest();
            inValue.Body = new Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.HelloWorldRequestBody();
            return ((Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaResponse Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap.EfetuaPesquisa(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequest request) {
            return base.Channel.EfetuaPesquisa(request);
        }
        
        public Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.Xml EfetuaPesquisa(string valorDaPesquisa) {
            Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequest inValue = new Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequest();
            inValue.Body = new Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequestBody();
            inValue.Body.valorDaPesquisa = valorDaPesquisa;
            Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaResponse retVal = ((Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap)(this)).EfetuaPesquisa(inValue);
            return retVal.Body.xml;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaResponse> Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap.EfetuaPesquisaAsync(Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequest request) {
            return base.Channel.EfetuaPesquisaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaResponse> EfetuaPesquisaAsync(string valorDaPesquisa) {
            Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequest inValue = new Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequest();
            inValue.Body = new Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.EfetuaPesquisaRequestBody();
            inValue.Body.valorDaPesquisa = valorDaPesquisa;
            return ((Proj270618_TesteAtak_AP.AtakWS_PesquisaGoogle.PesquisaGoogleSoap)(this)).EfetuaPesquisaAsync(inValue);
        }
    }
}
